#define MINIMP3_ONLY_MP3
//#define MINIMP3_ONLY_SIMD
#define MINIMP3_NO_SIMD
//#define MINIMP3_NONSTANDARD_BUT_LOGICAL
//#define MINIMP3_FLOAT_OUTPUT

#include "minimp3.h"
#define MINIMP3_IMPLEMENTATION
#include "minimp3.h"
#undef MINIMP3_IMPLEMENTATION